//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceONNX.Addons.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FaceONNX.Addons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] age_efficientnet_b2 {
            get {
                object obj = ResourceManager.GetObject("age_efficientnet_b2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] beauty_resnet18 {
            get {
                object obj = ResourceManager.GetObject("beauty_resnet18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] emotion_cnn {
            get {
                object obj = ResourceManager.GetObject("emotion_cnn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gender_efficientnet_b2 {
            get {
                object obj = ResourceManager.GetObject("gender_efficientnet_b2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
